# Generated by Django 2.0.13 on 2019-04-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_root', models.URLField(default='https://ref.tst.vng.cloud/ac/api/v1', unique=True, verbose_name='api root')),
                ('component', models.CharField(max_length=50, verbose_name='component')),
            ],
            options={
                'verbose_name': 'Autorisatiecomponentconfiguratie',
            },
        ),
    ]
