# Generated by Django 2.0.13 on 2019-04-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationsconfig',
            name='api_root',
            field=models.URLField(unique=True, verbose_name='api root'),
        ),
        migrations.AlterField(
            model_name='authorizationsconfig',
            name='component',
            field=models.CharField(choices=[('ZRC', 'ZRC'), ('ZTC', 'ZTC'), ('DRC', 'DRC'), ('BRC', 'BRC'), ('NC', 'NC'), ('AC', 'AC')], max_length=50, verbose_name='component'),
        ),
    ]
