# Generated by Django 2.1.8 on 2019-04-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20190429_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationsconfig',
            name='component',
            field=models.CharField(choices=[('ZRC', 'ZRC'), ('ZTC', 'ZTC'), ('DRC', 'DRC'), ('BRC', 'BRC'), ('NC', 'NC'), ('AC', 'AC')], default='ZRC', max_length=50, verbose_name='component'),
        ),
    ]
