# Generated by Django 3.2.14 on 2023-02-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0015_auto_20220318_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationsconfig',
            name='api_root',
            field=models.URLField(unique=True, verbose_name='api root'),
        ),
        migrations.AlterField(
            model_name='authorizationsconfig',
            name='component',
            field=models.CharField(choices=[('ac', 'Autorisaties API'), ('nrc', 'Notificaties API'), ('zrc', 'Zaken API'), ('ztc', 'Catalogi API'), ('drc', 'Documenten API'), ('brc', 'Besluiten API'), ('cmc', 'Contactmomenten API'), ('kc', 'Klanten API'), ('vrc', 'Verzoeken API')], max_length=50, verbose_name='component'),
        ),
    ]
