# Generated by Django 4.2.17 on 2025-02-10 13:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorizations", "0016_remove_authorizationsconfig_api_root_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicatie",
            name="client_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                help_text="Comma separated list of consumer identifiers (client_ids)",
                size=None,
                verbose_name="client IDs",
            ),
        ),
        migrations.AlterField(
            model_name="applicatie",
            name="heeft_alle_autorisaties",
            field=models.BooleanField(
                default=False,
                help_text="If all authorizations are given to this applicatie, no individual permissions have to be configured. Only enable this if you fully trust the consumer.",
                verbose_name="has all authorizations",
            ),
        ),
        migrations.AlterField(
            model_name="applicatie",
            name="label",
            field=models.CharField(
                help_text="A human readable representation of the application, for end users.",
                max_length=100,
            ),
        ),
    ]
