# Generated by Django 2.0.13 on 2019-05-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("audittrails", "0005_auto_20190520_1450")]

    operations = [
        migrations.AddField(
            model_name="audittrail",
            name="toelichting",
            field=models.CharField(
                blank=True,
                help_text="Toelichting waarom de handeling is uitgevoerd",
                max_length=200,
            ),
        )
    ]
