# Generated by Django 2.2.2 on 2019-06-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audittrails', '0007_auto_20190522_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='resource_weergave',
            field=models.URLField(default='', help_text='Vriendelijke identificatie van het object'),
            preserve_default=False,
        ),
    ]
