# Generated by Django 2.2.6 on 2020-06-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audittrails", "0011_auto_20190918_1335"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audittrail",
            name="bron",
            field=models.CharField(
                choices=[
                    ("ac", "Autorisatiecomponent"),
                    ("nrc", "Notificatierouteringcomponent"),
                    ("zrc", "Zaakregistratiecomponent"),
                    ("ztc", "Zaaktypecatalogus"),
                    ("drc", "Documentregistratiecomponent"),
                    ("brc", "Besluitregistratiecomponent"),
                    ("kic", "Klantinteractiescomponent"),
                ],
                help_text="De naam van het component waar de wijziging in is gedaan.",
                max_length=50,
            ),
        ),
    ]
