# Generated by Django 2.2.8 on 2020-11-06 08:58

from django.db import migrations, models

from ._operations import AddField


class Migration(migrations.Migration):

    dependencies = [
        ("audittrails", "0012_remove_audittrail_request_id"),
    ]

    operations = [
        AddField(
            model_name="audittrail",
            name="logrecord_id",
            field=models.CharField(
                blank=True,
                help_text='Een globaal "request" ID om een verzoek door het netwerk heen te traceren.',
                max_length=255,
            ),
        ),
    ]
