# Generated by Django 2.2.8 on 2020-10-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audittrails", "0012_auto_20200619_0545"),
    ]

    operations = [
        migrations.AddField(
            model_name="audittrail",
            name="logrecord_id",
            field=models.CharField(
                blank=True,
                help_text='Een globaal "request" ID om een verzoek door het netwerk heen te traceren.',
                max_length=255,
            ),
        ),
    ]
