# Generated by Django 2.2.8 on 2020-12-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audittrails", "0012_auto_20200619_0545"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audittrail",
            name="bron",
            field=models.CharField(
                choices=[
                    ("ac", "Autorisatiecomponent"),
                    ("nrc", "Notificatierouteringcomponent"),
                    ("zrc", "Zaakregistratiecomponent"),
                    ("ztc", "Zaaktypecatalogus"),
                    ("drc", "Documentregistratiecomponent"),
                    ("brc", "Besluitregistratiecomponent"),
                    ("cmc", "Contactmomenten API"),
                    ("kc", "Klanten API"),
                ],
                help_text="De naam van het component waar de wijziging in is gedaan.",
                max_length=50,
            ),
        ),
    ]
