# Generated by Django 2.2.17 on 2021-03-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audittrails", "0013_audittrail_logrecord_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audittrail",
            name="bron",
            field=models.CharField(
                choices=[
                    ("ac", "Autorisaties API"),
                    ("nrc", "Notificaties API"),
                    ("zrc", "Zaken API"),
                    ("ztc", "Catalogi API"),
                    ("drc", "Documenten API"),
                    ("brc", "Besluiten API"),
                ],
                help_text="De naam van het component waar de wijziging in is gedaan.",
                max_length=50,
            ),
        ),
    ]
