# Generated by Django 2.2.25 on 2022-01-11 15:23

import django.contrib.postgres.fields
from django.db import migrations, models

import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("audittrails", "0014_auto_20210323_1654"),
    ]

    operations = [
        migrations.AddField(
            model_name="audittrail",
            name="afdeling",
            field=models.CharField(
                blank=True,
                help_text="De afdeling waartoe de gebruiker behoort.",
                max_length=255,
                verbose_name="afdeling",
            ),
        ),
        migrations.AddField(
            model_name="audittrail",
            name="bedrijf",
            field=models.CharField(
                blank=True,
                help_text="Bedrijf waartoe de gebruiker behoort.",
                max_length=255,
                verbose_name="bedrijf",
            ),
        ),
        migrations.AddField(
            model_name="audittrail",
            name="kvk",
            field=vng_api_common.fields.RSINField(
                blank=True,
                help_text="KVK nummer van het bedrijf waartoe de gebruiker behoort.",
                max_length=9,
                verbose_name="kvk nummer",
            ),
        ),
        migrations.AddField(
            model_name="audittrail",
            name="rollen",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                default=list,
                help_text="Komma-gescheiden lijst van rollen van de gebruiker.",
                size=None,
                verbose_name="rollen",
            ),
        ),
    ]
