# Generated by Django 2.2.28 on 2022-06-07 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audittrails", "0015_auto_20220318_1608"),
        ("audittrails", "0014_auto_20210323_1654"),
    ]

    operations = []
