# Generated by Django 2.1.8 on 2019-09-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("testapp", "0002_auto_20190620_0849")]

    operations = [
        migrations.AddField(
            model_name="person",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        )
    ]
