# Generated by Django 2.1.8 on 2019-09-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("testapp", "0003_person__etag")]

    operations = [
        migrations.CreateModel(
            name="Hobby",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_etag",
                    models.CharField(
                        editable=False,
                        help_text="MD5 hash of the resource representation in its current version.",
                        max_length=32,
                        verbose_name="etag value",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="person",
            name="hobbies",
            field=models.ManyToManyField(
                blank=True, related_name="people", to="testapp.Hobby"
            ),
        ),
    ]
