# Generated by Django 2.1.8 on 2019-09-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("testapp", "0004_auto_20190909_0206")]

    operations = [
        migrations.AddField(
            model_name="group",
            name="name",
            field=models.CharField(default="", max_length=100, verbose_name="name"),
            preserve_default=False,
        )
    ]
