# Generated by Django 2.2.6 on 2020-04-16 04:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0003_auto_20200416_0423"),
        ("testapp", "0005_group_name"),
    ]

    operations = []
