# Generated by Django 3.2.16 on 2023-04-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0006_merge_20200416_0440"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="identificatie"
                    ),
                ),
                ("create_date", models.DateField(verbose_name="date")),
            ],
        ),
    ]
