# Generated by Django 4.1.13 on 2024-07-30 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0007_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poly",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "choice",
                    models.CharField(
                        choices=[("hobby", "Hobby."), ("record", "Record")],
                        max_length=6,
                        verbose_name="choice",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="record",
            name="create_date",
            field=models.DateField(verbose_name="create date"),
        ),
        migrations.CreateModel(
            name="FkModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "field_with_underscores",
                    models.CharField(max_length=100, verbose_name="name"),
                ),
                (
                    "poly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.poly",
                        verbose_name="poly",
                    ),
                ),
            ],
        ),
    ]
