# Generated by Django 3.2.25 on 2024-11-26 14:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0008_poly_alter_record_create_date_fkmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeometryModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "zaakgeometrie",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True,
                        help_text="Punt, lijn of (multi-)vlak geometrie-informatie.",
                        null=True,
                        srid=4326,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MediaFileModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("file", models.FileField(upload_to="uploads/", verbose_name="file")),
            ],
        ),
    ]
