# Generated by Django 2.1.8 on 2019-07-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("notifications", "0008_auto_20190502_0415")]

    operations = [
        migrations.AlterField(
            model_name="notificationsconfig",
            name="api_root",
            field=models.URLField(
                default="https://notificaties-api.vng.cloud/api/v1/",
                unique=True,
                verbose_name="api root",
            ),
        )
    ]
