# Generated by Django 5.1.2 on 2024-10-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0010_auto_20220704_1419"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="config",
        ),
        migrations.DeleteModel(
            name="NotificationsConfig",
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
