# Generated by Django 3.2.13 on 2022-06-28 12:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0010_auto_20220627_1340"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsconfig",
            name="failed_notification_admin_recipients",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                default=list,
                help_text="Komma-gescheiden lijst van emailadressen die een email moeten ontvangen als het niet gelukt is om een notificatie te versturen (na de laatste retry).",
                size=None,
                verbose_name="failed notification email admin recipients",
            ),
        ),
    ]
