name: Code quality checks

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  linting:
    name: Code-quality checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9', '3.10']
        django: ['3.2']
        zdsclient: ['1.0']
        toxenv:
          - isort
          - black
          - docs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install tox tox-gh-actions
      - run: |
          export TOXENV=py${PYTHON_VERSION/./}-django${DJANGO/./}-zdsclient${ZDS_CLIENT/./}
          tox
        env:
          TOXENV: ${{ matrix.toxenv }}
          ZDS_CLIENT: ${{ matrix.zdsclient }}


