name: code-quality-checks

on:
  push:
    branches:
      - master
      - stable/1.0.x
    tags:
      - '*'
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  isort:
    name: Code imports
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [ '3.7', ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install tox
      - name: Run isort
        run: tox -e isort

  black:
    name: Code format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.7', ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install tox
      - name: Run black
        run: tox -e black
